### ISSUE TITLE
Add banner saying that website is under construction

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/elixir-cloud-aai.github.io#22]
As not all content is ready or up-to-date, it would be good to have a warning banner that tells visitors that the website is under construction and may have missing, incomplete or outdated content. It should probably be part of the header so that it's visible on every page, and it should be set apart visually so that it's immediately obvious.

**Comment by git-anurag-hub** [comment]
Maybe like this: https://atlan.com ? @uniqueg 

Also user can have the functionality to cross/hide it.

**Comment by uniqueg** [comment]
Yeah, looks good. And yes, if visitors can hide it, even better :)
