### ISSUE TITLE
Add column for ORCID, ResearchGate, Google Scholar & GitHub to Contributors page

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/elixir-cloud-aai.github.io#6]
[ORCID](https://orcid.org/) is pretty much the _de facto_ standard for open sharing of researcher information. Users have the ability to maintain their pages and add research output, grants and CV-like info. Through their APIs, information can be independently validated by journals etc.

[ResearchGate](https://www.researchgate.net/) is somewhat similar, but is owned by a private company and lacks the independent validation features.

[Google Scholar](https://scholar.google.com/) similarly is owned by a private company, but it is used by lots of researchers to keep track of their publication lists.

Well, I guess I don't have to explain what GitHub is :)

Given how widespread all three of these are used, I guess it would make sense to include dedicated columns in the Contributors table, then show little icons like for LinkedIn on the contributor cards for all of them.

**Comment by git-anurag-hub** [comment]
Does [ORCID](https://orcid.org/), [ResearchGate](https://www.researchgate.net/) & [Google Scholar](https://scholar.google.com/) provides the profile links for the users?

**Comment by uniqueg** [comment]
Yes, they do. Google Scholar is an opaque identifier, some random string, but it's unique. The others give you something more human readable but also unique
